name: DragonEscape
main: com.comze_instancelabs.dragonescape.Main
version: 1.1
author: instancelabs
softdepend: [Vault]
commands:
   dragonescape:
      description: Main command
      usage: /dragonescape <action>
      aliases: [de]
